name: Run api tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1

      - run: npm install
        working-directory: ./a

      - run: npm run dev
        working-directory: ./api

      - run: npm test
        working-directory: ./api
