name: Run api tests

on: [push]

jobs:
  api-test:
    runs-on: ubuntu-latest
        
    services:
      postgres:
        image: postgres
        # refer: https://hub.docker.com/_/postgres
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
          POSTGRES_DB: sample
        ports:
          - 5432:5432
          
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1

      - run: npm install
        working-directory: ./

      - run: npm run migrate
        working-directory: ./

      - run: npm run seed
        working-directory: ./

      - run: nohup node ./src/index.js &
        working-directory: ./

      - run: npm test
        working-directory: ./
